### PR TITLE
track_number need to be converted to integer

### PR DESCRIPTION
**Pull request by Metice**
Sometimes $songInfo['comments']['track_number'] not contains an integer (for example "1/19"), you need to convert it.

### CODE REVIEW

**Comment by lGuillaume124** [comment]
Are you sure that's needful?

**Comment by Metice** [comment]
I managed my MP3s with Beets (http://beets.radbox.org/) and idtag v2 frame "comments" is dedicated to full text informations (http://id3.org/id3v2.3.0#Comments). I don't think it's a good idea to use this tag infos.
Another infos http://id3.org/id3v2.3.0#TRCK, as you can see, this field can be track number or track number / number of tracks.

**Comment by DiscoSeb** [comment]
I have the same problem and I use "TagScanner" to manage my MP3.
Add "intval" fix the problem.

**Comment by atomiix** [comment]
I added your pull request in my last commit,

**Pull request closed without merging**
