### PR TITLE
Fix #277

### LINKED ISSUE #277: Getting "Undefined index: id [APP/Model/User.php, line 152]" During Installation
Hi Trying to install 
but getting "Undefine index: id" notice with blank page

- 1
**Notice (8)**: Undefined index: id [**APP/Model/User.php**, line **152**]
**Warning (2)**: Cannot modify header information - headers already sent by (output started at lib/Cake/Utility/Debugger.php:794) [**CORE/Cake/Network/CakeResponse.php**, line **449**]
- 2
what files and directories should be Writable for installation ??

### PR DESCRIPTION
**Pull request by GaneshKandu**
https://github.com/Sonerezh/sonerezh/issues/277

### CODE REVIEW

**Comment by MightyCreak** [comment]
I'd suggest you replace the tabs with spaces like it was before, please.
Mixing the two always leads to problems, as we can see here, the diff is hard to read.
Thanks

**Comment by MightyCreak** [comment]
Could you propose the patch to @gs11's fork? https://github.com/gs11/sonerezh
It already has a bunch of features and fixes on top of the official dev branch.

**Comment by GaneshKandu** [comment]
closing bcoz made new pull request #319

**Comment by lGuillaume124** [comment]
Merged to ``development``. Thank you for your contribution.

**Pull request closed without merging**
