### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by nodiscc**
Fixes https://github.com/Sonerezh/sonerezh/issues/162

### CODE REVIEW

**Comment by nodiscc** [comment]
I'm on the wrong branch, right?

**Comment by lGuillaume124** [comment]
Yes, please make a pull-request branch from 'development'.
By the way we should add a contribution guide and clearly define how to contribute to Sonerezh :/

**Comment by nodiscc** [comment]
I will. Why no make `development` the default branch (in the github project settings)? It would prevent mistakes like this. I don't think there's a good reason to present the obsolete `master` branch to visitors.

**Comment by nodiscc** [comment]
#164

**Pull request closed without merging**
