### PR TITLE
Use GetID3 package from Composer

### LINKED ISSUE #343: Error on CLI import
I get PHP error during the CLI import process : 

```
Error: [] operator not supported for strings
#0 /[...]/app/Vendor/Getid3/module.audio.mp3.php(1085): getid3_mp3->decodeMPEGaudioHeader(5115, Array, false)    
#1 /[...]/app/Vendor/Getid3/module.audio.mp3.php(878): getid3_mp3->RecursiveFrameScanning(4634, 5115, true)   
#2 /[...]/app/Vendor/Getid3/module.audio.mp3.php(1417): getid3_mp3->decodeMPEGaudioHeader(4634, Array, true)      
#3 /[...]/app/Vendor/Getid3/module.audio.mp3.php(34): getid3_mp3->getOnlyMPEGaudioInfo(4608) 
#4 /[...]/app/Vendor/Getid3/getid3.php(428): getid3_mp3->Analyze()      
#5 /[...]/app/Lib/SongManager/SongManager.php(16): getID3->analyze('/mnt/disk1/mp3/...')        
#6 /[...]/app/Console/Command/SonerezhShell.php(117): SongManager->parseMetadata()  
#7 /[...]/lib/Cake/Console/Shell.php(459): SonerezhShell->import() 
#8 /[...]/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('import', Array)    
#9 /[...]/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#10 [...]/app/Console/cake.php(47): ShellDispatcher::run(Array)        
#11 {main}   

```
It's typical since PHP 7.1 version...
Maybe you should specify PHP version compatibilities ? (I use 7.2.9 currently)

### PR DESCRIPTION
**Pull request by MightyCreak**
The goal of this PR is to use GetID3 package from Composer instead of the old package included right now, and fix #343.

### Here's what I've done:

_This might not be the right way of doing things between CakePHP and Composer, I don't know much about those. Feel free to tell me how it should be done if there's a better way._

* By using Composer's GetID3 package, the old GetID3 package is no longer needed so I removed the `app/Vendor` directory (it's the vast majority of this PR content).

* Once that done, in order to have only one `Vendor` directory for all the Composer packages (i.e. CakePHP and GetID3), I changed Composer installation directory from `Vendor` to `app/Vendor`.

* Then I added `james-heinrich/getid3` in `composer.json` (and remove `ext-gd` since it doesn't seem to be a valid Composer package).

* Then I included the `app/Vendor/autoload.php` in `bootstrap.php` to be able to easily instantiate classes from the `Vendor` directory.

* And finally I changed `CAKE_CORE_INCLUDE_PATH` to point to `app/Vendor` and I removed the `App::import` from `SongManager.php`.

### CODE REVIEW

**Comment by lGuillaume124** [comment]
When we tried to update this lib from ``1.9.7-20130705`` to the very next version we noticed it was a little bit longer to fetch the cover arts. That's why we didn't upgrade it but it seems to be required now…

**Comment by MightyCreak** [comment]
Ok so I tested the import of my library (2597 files) with the old and the new GetID3 lib, using the command line (because it's easier to benchmark like that):
* Old: 25s
* New: 1min58s

That's clearly much longer (x4), but from my perspective, it's not that bad since it only affects the import. It would surely have been nicer if it has been faster, but I think using a package that is easy to upgrade is more valuable that the added delay during the import. Maybe GetID3 v2 that is in preview at the moment tries to address that?

PS: By using the command line, I saw that there was a problem with the new CakePHP path there, so I fixed it: 6e7572d1734f60f4f385e39a5d2d882a78de75b9.

**Comment by MightyCreak** [comment]
I updated the CHANGELOG as well (the "Unreleased" section is a good practice I got from https://keepachangelog.com/)

**Comment by MightyCreak** [comment]
@lGuillaume124 I know you're in the new database refactor, but since this PR also fixes #343, would you consider merging it?

@gs11 would you like to review it as well?

**Comment by lGuillaume124** [comment]
As the « WIP » label was still here I thought you were still working on it.

**Comment by gs11** [comment]
LGTM, great work!

**Comment by gs11** [comment]
LGTM, great work! @MightyCreak

**Comment by MightyCreak** [comment]
I was expecting to have done something bad so I didn't remove the "WIP" flag 😅

**Pull request merged**
