### PR TITLE
Fix language typos.

### PR DESCRIPTION
**Pull request by MightyCreak**
Very simple fix: "wan" -> "want" and a missing space in the end of a french translation.

### CODE REVIEW

**Comment by MightyCreak** [comment]
No news about this PR. Is there a problem with it?

**Comment by lGuillaume124** [comment]
No don't worry. I jut haven't had time to look at it... I will merged it as soon as possible.

**Comment by MightyCreak** [comment]
I've just seen that there is a "development" branch, would you prefer if I rebase my commit on this branch?

**Comment by lGuillaume124** [comment]
Yes please.

**Pull request closed without merging**
