### PR TITLE
Buffer songs preemtively to avoid waiting on song change

### PR DESCRIPTION
**Pull request by DavidVentura**
I should've done something to pre-calculate the next random song to be able to buffer it

### CODE REVIEW

**Comment by MightyCreak** [comment]
I'd really like to see that in the next release!

**Comment by atomiix** [comment]
Hi,

I forgot to had a reference to this PR when I anwered #179 but here is what I said : 

> I was looking for merge your PR but it seems that creating another audio element and loading the next song is not enough, the main audio element will reload the next song anyway.
> In addition, it's hard to see because when using a local environment it loads songs very fast.
> But in chrome, you can throttle the bandwidth speed in the developer console.
> 
> I'm still looking for a good solution to preload the next song, if you have any idea, let me know 😉

**Comment by DavidVentura** [comment]
On Firefox I get a 200 on first access, but when the real player requests the file I get a 302 and its instant. 

On July 3, 2016 1:52:05 PM GMT-03:00, atomiix <notifications@github.com> wrote:
>Hi,
>
>I forgot to had a reference to this PR when I anwered #179 but here is
>what I said : 
>
>> I was looking for merge your PR but it seems that creating another
>audio element and loading the next song is not enough, the main audio
>element will reload the next song anyway.
>> In addition, it's hard to see because when using a local environment
>it loads songs very fast.
>> But in chrome, you can throttle the bandwidth speed in the developer
>console.
>> 
>> I'm still looking for a good solution to preload the next song, if
>you have any idea, let me know 😉
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Sonerezh/sonerezh/pull/114#issuecomment-230162972

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lGuillaume124** [comment]
Hi,
Thanks for your work, could you _rebase_ your branch on ``development`` please?

**Pull request closed without merging**
