### PR TITLE
Auto creating playlists based on folder structure

### LINKED ISSUE #278: Auto creating playlists based on folder structure
I think that autocreating playlists based on folder structure is very useful feature.
So i try to implement it. But i faced a problem i don't know how to create PlaylistMembership instance with song_id and playlist_id. So my current solution looks like:
`Controller/SongsController.php`
```php
$this->Song->query("INSERT INTO `playlist_memberships` VALUES (NULL, $playlist_id, $song_id, 0);");
```
Any ideas how to make it better to let me public my solution?
Something like:
```php
$data = array();
$data['PlaylistMembership'] = array('song_id' = $song_id, 'playlist_id' = $playlist_id, 'order' = 0);
$this->PlaylistMembership->save($data);
```

### PR DESCRIPTION
**Pull request by monomops**
Closes #278 .
Creats new playlists and filling it with songs while "Updating databse".
Uses last folder from path/to/file as name of playlist.

### CODE REVIEW

**Comment by MightyCreak** [comment]
Does it create a playlist for each and every folders in the root dir? All my musics are stored in a `<artist>/<album>/` pattern. I would have as much playlist as I have albums?

It's my personal opinion as a user, I'm not a dev of Sonerezh. I'm not very fond of this kind of auto generation based on folder structure. IMO folders structure and UI representations should not be tied together. Folders are here to organize, no less, no more. There should be no meta data to get from them.

Moreover, and even if I am no playlist user myself, I think playlists should be made by the users and then shared between them. I see Sonerezh as a personal Spotify/Deezer, that might, one day, even become a distributed (like ownCloud/Nextcloud). So having your playlist automatically generated is nice for a personal user standpoint, but less relevant as a multi-users, multi-servers point of view.

That being said, I understand that it's frustrating to have your playlist wiped out each time you erase you DB because you removed out just one song... (though there's a workaround for that). And for that, I think Sonerezh playlists should be exportable/importable in the future.

And because just criticizing doesn't get us very far, I propose another solution: the [M3U playlist format](https://en.wikipedia.org/wiki/M3U) is well known and maybe Sonerezh could parse a `playlists/` directory where it would read the M3U files and create playlists based on that.

Later, each user could have there own playlist directories and could create one, share it, or even download all the songs from it.

**Comment by monomops** [comment]
You right. It will generate playlist for every album you have. 

Okay, i see this idea is not flawless. Not solution for every one. I used to store music in folders like situational playlist. So i have about 15 folders with various music. I want to listen music from exact folder - now it is impossible to sort somehow music by folder. My idea was to create auto_generated playlists to let users like me use Sonerezh auto-of-a-box. 

As Sonerezh doesn't support per-user songs uploading, for me implementing predefined playlist is not bad idea. Probably it should be configurabal through Install process some kind of checkbox saying "Generate playlist per folder'.

**Comment by MightyCreak** [comment]
If you code a M3U importer in Sonerezh, you will then be able to generate the M3U on your side based on your folders and import them using just the console. It would be one script for you to run once you've updated your DB. Maybe there are some commands missing (like remove all playlists), but that shouldn't be very hard to code.

As you said, the problem with basing algorithm on the folders structure is that not everyone organizes their music the same way and that would lead to different, probably undesirable results.

**Comment by lGuillaume124** [comment]
I like the idea with the M3U format.

**Pull request closed without merging**
