### PR TITLE
Implemented database cleaning

### PR DESCRIPTION
**Pull request by gs11**
Files no longer found on the file system are now removed as part of the database update process.
Thus, import has been renamed to update in some parts of the view.

This fixes issue #129

### CODE REVIEW

**Comment by MightyCreak** [comment]
LGTM

**Comment by ltGuillaume** [comment]
This doesn't remove unused cover art.

**Comment by gs11** [comment]
Good point, I'll fix that. I guess playlist membership should be removed as well if the database design doesn't use cascade for deletes.

**Comment by MightyCreak** [comment]
> I guess playlist membership should be removed as well if the database design doesn't use cascade for deletes.

If we want to do something very nice (maybe a v2), the deleted songs should go into a "deleted_songs" table. Then the playlist will show the song grayed with a text message "Song has been removed". If there are no more dependencies like that, then the song can be removed from the "deleted_songs" table.

**Comment by gs11** [comment]
@ltGuillaume Cover art & playlist membership removal now implemented

**Comment by gs11** [comment]
@MightyCreak Yeah, that might be feasible in the future. I took the simpler road for this pull req.

**Comment by ltGuillaume** [comment]
@gs11 I don't think this will work: as far as I remember, the names of the cover art files are MD5 checksums, so if a song's cover art results in the same file, with the same checksum, it will re-use the existing file. So the relation cover art - song is one to many. I had a glance at your code, and it seems you'll remove the cover art even if other songs are using these files as cover art.

**Comment by MightyCreak** [comment]
@gs11 That's really all right, I am already glad you did this feature since I was waiting for someone to do it for a very long time! ;)

@ltGuillaume About the MD5 checksums, I guess the MD5 is based on the song file? If it is, then I guess the idea would be to do `SELECT COUNT(*) FROM songs WHERE cover == '<the md5>.jpeg'`, if there is no result, we can remove the cover!

**Comment by gs11** [comment]
@MightyCreak @ltGuillaume  I'll add a lookup to make sure that the covers are only removed once all references are gone. The MD5 is btw based on the artist & album.

Btw, what has happened to the project/developers? The pull request queue is growing.

**Comment by ltGuillaume** [comment]
I think I did this exactly the same way in my piece of code, yeah, just  SELECT COUNT.

I think I remember that the import process via web UI vs the import process via the command line interface is completely separate, so you'll have to implement these changes twice, correct?

**Comment by ltGuillaume** [comment]
I think I did this exactly the same way in my piece of code, yeah, just  SELECT COUNT.

I think I remember that the import process via web UI vs the import process via the command line interface is completely separate, so you'll have to implement these changes twice, correct?

This was my code https://github.com/ltGuillaume/sonerezh/commit/6d0ffa7da42730be1932b905db79c0f26265ebb9 but it's based on an older development commit, so things might have changed,

**Comment by gs11** [comment]
Finally got around to look at this again.
However, I'm struggling with getting CakePHP to work with my query.

Working SQL statement:
```
SELECT s1.id, s1.cover, COUNT(s2.id) files_with_cover FROM songs s1 INNER JOIN songs s2 ON s2.cover=s1.cover WHERE s1.source_path=$path`
```

CakePHP version:
```
$result = $this->Song->find('first', array(
    'joins' => array(
        array(
            'table' => 'songs',
            'alias' => 'Song2',
            'type' => 'INNER',
            'conditions' => array('Song2.cover = Song.cover')
        )
    ),
    'fields' => array('Song.id', 'Song.cover', 'count(Song2.id)'),
    'conditions' => array('source_path' => $file)
));
```

However, the query only hangs here. The idea is to only delete the cover if count is 1.
Other alternatives are:
- Do a separate query to check files with cover (I'd like to avoid this)
- Use raw sql ($this->Song->query('SELECT [...]')

Any ideas?

**Comment by ltGuillaume** [comment]
I think it's a little bit complicated, that's for sure :P 

I just did this after I removed the song.
```
if (!empty($cover) && $this->Song->find('count', array('conditions' => array('cover' => $cover))) == 1) {
delete cover file...
}
```
I think my code here https://github.com/ltGuillaume/sonerezh/commit/6d0ffa7da42730be1932b905db79c0f26265ebb9 might be hacky, I don't know (and it's only for the command line interface), but it has been working fine for months.

**Comment by gs11** [comment]
Fixed the above query issue, my condition was ambiguous since _source_path_ exist in both joined table.
Found out that there are logs written at <sonerezh root>/app/tmp/logs which were very helpful.

However, somehow the query returns two rows where the first row contains id & cover and the second contains the count. Troubleshooting..

**Comment by gs11** [comment]
Ok, issues resolved and this now seems to work just fine! Merging to my development-new branch

**Pull request merged**
